version: '3.8'

services:
  # Homeskillet Orchestrator
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.monorepo
    container_name: homeskillet-orchestrator
    ports:
      - "8080:8080"    # HTTP API
      - "8443:8443"    # HTTPS API
      - "9090:9090"    # Metrics
    environment:
      - RUST_LOG=info
      - HOSTED_AI_BASE_URL=${HOSTED_AI_BASE_URL:-https://api.hosted.ai}
      - HOSTED_AI_API_KEY=${HOSTED_AI_API_KEY}
      - HOSTED_AI_POOL_ID=${HOSTED_AI_POOL_ID:-standard}
      - HOSTED_AI_OVERCOMMIT=${HOSTED_AI_OVERCOMMIT:-false}
      - REDIS_URL=redis://redis:6379
      - PROMETHEUS_ENDPOINT=http://prometheus:9090
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - redis
      - prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - homeskillet-net

  # MCP WebSocket Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.monorepo
    container_name: homeskillet-mcp
    command: ["/app/bin/mcp-server"]
    ports:
      - "8765:8765"    # WebSocket
    environment:
      - RUST_LOG=info
      - ORCHESTRATOR_URL=http://orchestrator:8080
      - WEBSOCKET_PORT=8765
    depends_on:
      - orchestrator
    restart: unless-stopped
    networks:
      - homeskillet-net

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: homeskillet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - homeskillet-net

  # Prometheus Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: homeskillet-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - homeskillet-net

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: homeskillet-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - homeskillet-net

  # Jaeger Tracing (Optional)
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: homeskillet-jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"    # UI
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    networks:
      - homeskillet-net

  # NGINX Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: homeskillet-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - orchestrator
      - mcp-server
      - grafana
    restart: unless-stopped
    networks:
      - homeskillet-net

volumes:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  homeskillet-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16