# Prometheus configuration for Homeskillet POC

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'homeskillet-poc'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Homeskillet Orchestrator metrics
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # MCP Server metrics
  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Custom metrics for Hosted.AI integration
  - job_name: 'hosted_ai'
    static_configs:
      - targets: ['orchestrator:9090']
    metrics_path: '/metrics/hosted_ai'
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'hosted_ai_.*'
        action: keep